version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: news-aggregator-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - backend-data:/app/output
    expose:
      - "8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: news-aggregator-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd:ro

volumes:
  backend-data:
