# syntax=docker/dockerfile:1

FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps

COPY frontend/ ./
RUN npm run build


FROM nginx:1.27-alpine

RUN mkdir -p /usr/share/nginx/html \
	&& mkdir -p /etc/nginx/certs

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/.htpasswd /etc/nginx/conf.d/.htpasswd

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]

