# Конфигурация для новостного агрегатора

# Настройки API для суммаризации
api:
  # Используем OpenRouter API
  openrouter:
    base_url: "https://openrouter.ai/api/v1"
    model: "deepseek/deepseek-chat-v3.1:free"
    temperature: 0.7
    max_tokens: 1000

# Настройки парсинга новостей
news:
  # Количество новостей для сбора из каждого источника
  max_news_per_source: 7
  
  # Количество топ-новостей дня
  top_news_count: 5

# RSS источники по категориям (по 3 лучших источника на категорию)
rss_sources:
  технологии:
    - url: "https://habr.com/ru/rss/hub/artificial_intelligence/all/"
      name: "Habr AI"
    - url: "https://techcrunch.com/feed/"
      name: "TechCrunch"
    - url: "https://vc.ru/rss"
      name: "VC.ru"
  
  бизнес:
    - url: "https://www.rbc.ru/v10/rss/news/30/full.rss"
      name: "РБК Новости"
    - url: "https://www.forbes.ru/rss"
      name: "Forbes Russia"
    - url: "https://www.vedomosti.ru/rss/news"
      name: "Ведомости"
  
  наука:
    - url: "https://nplus1.ru/rss"
      name: "N+1"
    - url: "https://elementy.ru/rss/news"
      name: "Элементы"
    - url: "https://phys.org/rss-feed/"
      name: "Phys.org"
  
  общее:
    - url: "https://lenta.ru/rss"
      name: "Lenta.ru"
    - url: "https://tass.ru/rss/v2.xml"
      name: "TASS"
    - url: "https://meduza.io/rss/all"
      name: "Meduza"
  
  развлечения:
    - url: "https://www.ign.com/feed.xml"
      name: "IGN"
    - url: "https://dtf.ru/rss/all"
      name: "DTF"
    - url: "https://stopgame.ru/rss/rss_news.xml"
      name: "StopGame"
  
  спорт:
    - url: "https://www.sports.ru/rss/all_news.xml"
      name: "Sports.ru"
    - url: "https://www.championat.com/rss/news.xml"
      name: "Чемпионат"
    - url: "https://www.espn.com/espn/rss/news"
      name: "ESPN"
